import {
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Bookmark,
  BookOpen,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleUserRound,
  Copy,
  CreditCard,
  FastForward,
  Flag,
  GitFork,
  Home,
  Heart,
  Info,
  LibraryBig,
  List,
  LogOut,
  Menu,
  Minus,
  MoreVertical,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Share2,
  Settings,
  ShieldCheck,
  Sparkles,
  Square,
  Star,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

const icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  ban: Ban,
  bell: Bell,
  bookmark: Bookmark,
  book: BookOpen,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  copy: Copy,
  create: Plus,
  credits: Sparkles,
  delete: Trash2,
  discover: Home,
  edit: Pencil,
  fastForward: FastForward,
  flag: Flag,
  heart: Heart,
  info: Info,
  library: LibraryBig,
  list: List,
  logout: LogOut,
  menu: Menu,
  minus: Minus,
  more: MoreVertical,
  moreHorizontal: MoreHorizontal,
  persona: CircleUserRound,
  regenerate: RefreshCw,
  search: Search,
  send: Send,
  share: Share2,
  settings: Settings,
  shield: ShieldCheck,
  sparkle: Sparkles,
  stop: Square,
  star: Star,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  branch: GitFork,
  close: X,
  billing: CreditCard,
} as const satisfies Readonly<Record<string, LucideIcon>>;

export type VeloraIconName = keyof typeof icons;

export interface VeloraIconProps extends Omit<LucideProps, 'children' | 'name' | 'aria-label'> {
  readonly name: VeloraIconName;
}

export function VeloraIcon({ name, size = 20, strokeWidth = 2, ...props }: VeloraIconProps) {
  const Icon = icons[name];
  return (
    <Icon aria-hidden="true" focusable="false" size={size} strokeWidth={strokeWidth} {...props} />
  );
}
